spring:
  server:
    port: 8080
  cloud:
    gateway:
      routes:
      - id: home_route
        uri: http://localhost:8000
        predicates:
        - Path=/**
      - id: google_route
        uri: http://www.google.com
        predicates:
        - Path=/google/